### ISSUE TITLE
Feature : Adding Animated icons in the contact us page

### ISSUE THREAD

**Issue by SadafKausar2025** [Mansi168/EmoWell#103]
before
![Screenshot (1731)](https://github.com/Mansi168/EmoWell/assets/137484958/993f3475-b0d4-40d7-a582-40d321425c84)

after

https://github.com/Mansi168/EmoWell/assets/137484958/455cb98d-63a0-401c-94e7-5438b01806fb

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me #103?

**Comment by everly-gif** [comment]
@SadafKausar2025 if you are interested you can pick this up.
