### ISSUE TITLE
[Bug] Missing Review Page 

### ISSUE THREAD

**Issue by Manav173** [Mansi168/EmoWell#105]
Problem:
Currently, the website lacks a dedicated space for users to provide feedback or report any issues they encounter while using the platform.

Solution:
Implement a review page which will serve as a centralized hub for collecting user feedback, enabling us to enhance the user experience and resolve any issues efficiently.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @Mansi168  .

**Comment by Mansi168** [comment]
sure, go ahead!

**Comment by Manav173** [comment]
As the PR #125 is merged, I am closing this issue.
