### ISSUE TITLE
Updating Contact Page

### ISSUE THREAD

**Issue by PratikMane0112** [Mansi168/EmoWell#112]
Current contact page is not attractive - 

![Screenshot 2024-05-17 010355](https://github.com/Mansi168/EmoWell/assets/153143167/061191bb-000b-45de-aad5-8555b932fb7a)

Also not responsive - 

![Screenshot 2024-05-17 010731](https://github.com/Mansi168/EmoWell/assets/153143167/7ee54691-d43f-4a0a-913f-ae605453f9d6)

I will make more attractive and responsive. Plz assign this task to me.

**Comment by annoy004** [comment]
can you please assign me this issue

**Comment by Agarwalvidu** [comment]
@PratikMane0112 Can you please elaborate what changes you want to make?

**Comment by PratikMane0112** [comment]
> @PratikMane0112 Can you please elaborate what changes you want to make?
Making it responsive, adaptive to mobile screen

**Comment by Agarwalvidu** [comment]
@PratikMane0112 Assigning!
