### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [Mansi168/EmoWell#144]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by everly-gif** [comment]
We do now have a github actions setup for auto commenting on when a PR is raised. Thanks ! If you meant something else please raise a PR with all details clearly.

**Comment by suhanipaliwal** [comment]
> We do now have a github actions setup for auto commenting on when a PR is raised. Thanks ! If you meant something else please raise a PR with all details clearly.

This issue is regarding adding a comment after a pull request is merged not for raising a pr.
