### ISSUE TITLE
[Bug]: Content in Privacy Policy is not perfectly aligned centre

### ISSUE THREAD

**Issue by upsaurav12** [Mansi168/EmoWell#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we go ``privacy policy`` page we can see the content are not horizontally centred. You can see in this pic 
![image](https://github.com/Mansi168/EmoWell/assets/116784047/f014316a-a742-475e-b886-21b832bb3c73)
and also in mobile view it should adjust their fonts as they are not uniform

### Add ScreenShots

![image](https://github.com/Mansi168/EmoWell/assets/116784047/b4cbe2e7-3cff-4741-9300-63a5e433b17a)
![image](https://github.com/Mansi168/EmoWell/assets/116784047/f6f46903-a88c-4849-bc25-c8dd93a02cbc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by upsaurav12** [comment]
@Mansi168 pls assign me this issue under gssoc

**Comment by everly-gif** [comment]
Since we have a new ui for it now. this issue is not relevant, thanks
