### ISSUE TITLE
[Documentation Update]: Add Code of Conduct 

### ISSUE THREAD

**Issue by aasthakourav20** [Mansi168/EmoWell#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

A Code of Conduct is crucial for maintaining a respectful and inclusive community. It sets clear expectations for behavior and outlines the steps for reporting and addressing unacceptable behavior. Here’s why it’s important:

Sets Behavioral Expectations: It clearly defines acceptable and unacceptable behavior, helping to create a welcoming and inclusive environment for all participants.
Promotes Respect and Inclusivity: It encourages respect and inclusivity, ensuring that everyone feels safe and valued within the community.
Conflict Resolution: It provides guidelines on how to handle conflicts and what actions will be taken in response to violations, promoting fairness and transparency.

### Suggested Change

Adding a file of Code of Conduct.

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, we already have an existing issue opened on the same requirement. Closing this as duplicate.
