### ISSUE TITLE
Not Responsive Website

### ISSUE THREAD

**Issue by Che140401** [Mansi168/EmoWell#15]
Website is not responsive,

please assign it to me i will make it responsive,

Name:Chetan Karande;
Work Experience:Front End Developer
Linkedin:www.linkedin.com/in/chetan-karande-b8b33b238

**Comment by nitin-pandita** [comment]
I would like to work on this issue please assign me this issue

**Comment by Mansi168** [comment]
> Website is not responsive,
> 
> please assign it to me i will make it responsive,
> 
> Name:Chetan Karande; Work Experience:Front End Developer Linkedin:www.linkedin.com/in/chetan-karande-b8b33b238

Sure, please go ahead.

**Comment by Che140401** [comment]
Thankyou i will try my best

**Comment by Che140401** [comment]
**Live site error**

![nav-bar-error-live](https://github.com/Mansi168/EmoWell/assets/109230049/921ce5cb-9731-4df7-a170-f7301e2ab504)
![2nd-Live error](https://github.com/Mansi168/EmoWell/assets/109230049/80684c59-34da-443f-a559-b32d068cf4e4)
![3rd-error lIVE](https://github.com/Mansi168/EmoWell/assets/109230049/859dc353-31c1-450b-a2a9-977a778bf566)
![4th-mobile live error](https://github.com/Mansi168/EmoWell/assets/109230049/15d2e33e-093a-4cc6-b5c5-27b5e27de441)

**Error Solved**
![1st_problem_solved](https://github.com/Mansi168/EmoWell/assets/109230049/f5f9f968-aa3f-4cec-a38a-cb940cf27d72)
![2nd_problem_solved](https://github.com/Mansi168/EmoWell/assets/109230049/8b4e8be8-aa2d-4c4a-a010-9d7e44b2d290)
![3rd problem_solved](https://github.com/Mansi168/EmoWell/assets/109230049/17fc6091-fe69-4ce5-8417-e026e81d7205)


![4th problem solved](https://github.com/Mansi168/EmoWell/assets/109230049/452199d8-ebd7-442d-a083-8f3cb321139f)


**Website is looking awesome now**

**Comment by Che140401** [comment]
**Mobile tab all errors in responsiveness solved**

**Comment by Mansi168** [comment]
Please open a pull request for review!

**Comment by Che140401** [comment]
> Please open a pull request for review!

please check pull request

**Comment by everly-gif** [comment]
@Che140401
https://github.com/Mansi168/EmoWell/pull/35
has review comments from the maintainer , please address them.
If you face any issues in doing so contact me or the maintainer via discord.
Due to the time taken for the resolvation of this issue, we need a response ASAP, possibly by tomorrow . Otherwise this issue will be assigned to the next interested assignee.

**Comment by everly-gif** [comment]
@nitin-pandita are you up for it? previous assignee was unresponsive.
