### ISSUE TITLE
[Feature Request]:  Added FAQ's Page

### ISSUE THREAD

**Issue by dhruv8433** [Mansi168/EmoWell#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Mansi168 

we can add faqs page on route `/faqs`
it will help user to find solution of their particular questions like 
1. how to register on EmoWell etc...

### Use Case

when user will visit `/faqs` it look like
![image](https://github.com/Mansi168/EmoWell/assets/114583978/63654f11-d0d8-44ad-9791-fb8813d6ea2e)

### Benefits

it will help use to find solution about particular questions

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, we already have added a FAQ page, thanks!
