### ISSUE TITLE
[Bug]:  Contact us overflow 

### ISSUE THREAD

**Issue by dhruv8433** [Mansi168/EmoWell#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Mansi168 

in responsive, contact us form overflow and go outside the screen
we have to center it and make it responsive

### Add ScreenShots

![image](https://github.com/Mansi168/EmoWell/assets/114583978/67bc664f-aead-4e4f-b135-2e6571803bea)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by gopalepic** [comment]
@Mansi168 can you assign this to me , I can make the contribution

**Comment by Agarwalvidu** [comment]
This page is rebuilt with proper responsiveness. Thank you for collaborating. Looking for more issues from your side. For the same reason I am closing this issue.
