### ISSUE TITLE
[Feature Request]: add hover effect on our feature

### ISSUE THREAD

**Issue by Ketanop321** [Mansi168/EmoWell#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no hove effect on cards on out features

### Use Case

Highlighting the background of card in hover

### Benefits

Increase use experience 

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
We have a issue already opened for this
