### ISSUE TITLE
Adding footer in contact and review page

### ISSUE THREAD

**Issue by dhairyagothi** [Mansi168/EmoWell#172]
hey @Mansi168 i can add footer in contact and review page 
please assign this to me with label gssoc

## Please add footer in the following routes

- [ ] contact
- [ ] review
- [ ] reading

**Comment by KavyaBS123** [comment]
Hey @Mansi168 I am GSSOC contributor can you please assign this issue to me I would like to work on it!

**Comment by everly-gif** [comment]
@dhairyagothi issue is yours! please also add in reading section as well

**Comment by dhairyagothi** [comment]
okay but please assign level 2 😢 thanks

**Comment by dhairyagothi** [comment]
@everly-gif please merge PR i have added

**Comment by everly-gif** [comment]
> okay but please assign level 2 😢 thanks

Hey sorry, buts a one-liner change in 3 files

**Comment by dhairyagothi** [comment]
> > okay but please assign level 2 😢 thanks
> 
> Hey sorry, buts it's a  one-liner change in 3 files

Ya sorry i also saw that assign level 1 only
