### ISSUE TITLE
Error after clicking the register button

### ISSUE THREAD

**Issue by CoderGirl2844** [Mansi168/EmoWell#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On clicking the register button, it shows an error page akso the favicon is missing for that page

![Screenshot 2024-06-05 202353](https://github.com/Mansi168/EmoWell/assets/155231566/690204f1-d51b-48e7-b0e1-7419d6c4208a)
Please assign this issue to me 
I can design the register page and add favicon to it 

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
This issue can only be fixed by admin as she has the auth0 credentials and can configured the allowed callback urls. Thanks!
