### ISSUE TITLE
Add a star rating feature in review form

### ISSUE THREAD

**Issue by ananyag309** [Mansi168/EmoWell#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Mansi168 as you can see in review rating we can give 1-5 but i just input 6 below. I would like to replace that rating with star it would be much easier and will improve the ui/ux of review page
![rating](https://github.com/Mansi168/EmoWell/assets/145869907/9eb4b699-784d-4f3c-92a4-de95128d37b4)

### Use Case

The feature will enhance the ui/ux of review form

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sidhi2001** [comment]
Hey 
I am GSSOC contributor can you please assign this issue to me I would like to work on it!

**Comment by everly-gif** [comment]
We have a new renewed review form but thank you for suggesting
