### ISSUE TITLE
[Bug]: Scroll To Top Button Visibility

### ISSUE THREAD

**Issue by pani2004** [Mansi168/EmoWell#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The scroll to top button should only be visible when the user scrolls down the page , but now even at the top of the page the button is visible

### Add ScreenShots

![Screenshot (50)](https://github.com/Mansi168/EmoWell/assets/154724111/9746f5c0-c134-45e9-8c3b-d305d6b347cf)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pani2004** [comment]
@Mansi168 Pls assign me this!!

**Comment by pani2004** [comment]
@Mansi168 pls review this

**Comment by pani2004** [comment]
@everly-gif review this issue

**Comment by pani2004** [comment]
@Mansi168 Can I work on this?

**Comment by pani2004** [comment]
@Agarwalvidu pls review this and assign

**Comment by everly-gif** [comment]
@pani2004 assigned
