### ISSUE TITLE
[Bug]: registration page is not working

### ISSUE THREAD

**Issue by Isha1233** [Mansi168/EmoWell#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

on clicking on register its showing error.

### Add ScreenShots

![WhatsApp Image 2024-06-06 at 23 56 22 (1)](https://github.com/Mansi168/EmoWell/assets/120541874/b8f08efc-31c6-4863-a91a-71ac4b3cbfb2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Isha1233** [comment]
@Mansi168 kindly assign this issue to me

**Comment by everly-gif** [comment]
This can only be fixed by someone who has auth0 dashboard credentials ie. @Mansi168. So that the correct call back url is configured and allowed from auth0
