### ISSUE TITLE
[Feature Request]: login / signup backend

### ISSUE THREAD

**Issue by Isha1233** [Mansi168/EmoWell#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will implement it using nodejs and MongoDB

### Use Case

making it readable 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, there is the functionality already created with auth0 which collects user data. I personally don't see a need for this
