### ISSUE TITLE
[Feature Request]: backend functionality of login/register with google

### ISSUE THREAD

**Issue by Isha1233** [Mansi168/EmoWell#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

using firebase I will implement it 

### Use Case

readable 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Isha1233** [comment]
@Mansi168 kindly assign this issue to me

**Comment by Khushi-Pushkar** [comment]
@Mansi168  @everly-gif please assign

**Comment by everly-gif** [comment]
Hi, there is already an login functionality with auth0 which collects users data. So I personally don't see a need for this.
