### ISSUE TITLE
[Bug]: Header needs to be responsive

### ISSUE THREAD

**Issue by kapilG0** [Mansi168/EmoWell#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Mansi168/EmoWell/assets/59639410/9373cf4c-3092-4851-888d-735531af09d7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kapilG0** [comment]
Hello @Mansi168 please assign this issue to me under gssoc 24

**Comment by Agarwalvidu** [comment]
@kapilG0 Go ahead!

**Comment by everly-gif** [comment]
Outdated
