### ISSUE TITLE
[Bug]: in review section submit button not showing in mobile

### ISSUE THREAD

**Issue by kapilG0** [Mansi168/EmoWell#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Mansi168/EmoWell/assets/59639410/ea9546f5-4a64-4032-a106-b8627db6a2b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kapilG0** [comment]
Hello @Mansi168 please assign this issue to me under gssoc 24

**Comment by everly-gif** [comment]
@kapilG0 please take the issue
