### ISSUE TITLE
[Bug]: Privacy And Policy link  Not Scrolling to Top of page

### ISSUE THREAD

**Issue by Satuti99** [Mansi168/EmoWell#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This bug involves a situation where clicking on the privacy and policy link does not result in scrolling to the top of the privacy page or section. Instead, the user remains on the same line or position within the privacy content, causing navigation confusion and potentially affecting user experience.

### Add ScreenShots

https://github.com/Mansi168/EmoWell/assets/115169702/4eb459c5-0b15-4d39-b537-ce74a903e3ff

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
@Satuti99 pls proceed

**Comment by Satuti99** [comment]
Respected ma'am please add labels in my PR for leaderboard.

![image](https://github.com/user-attachments/assets/1e631989-b720-4dad-9b71-21d00c0302b1)

**Comment by everly-gif** [comment]
> Respected ma'am @everly-gif please add labels in my PR for leaderboard.
> 
> ![image](https://private-user-images.githubusercontent.com/115169702/352061132-1e631989-b720-4dad-9b71-21d00c0302b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQyMTEsIm5iZiI6MTcyMTkwMzkxMSwicGF0aCI6Ii8xMTUxNjk3MDIvMzUyMDYxMTMyLTFlNjMxOTg5LWI3MjAtNGRhZC05YjcxLTIxZDAwYzAzMDJiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDM4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTc3MzljMjY1MDU5NTI4MDI5YjE0NDQ5MmYzNDI1MjI3ZGJkZmM2MGUwY2Y1NmMyN2MzZDEwNjQ4YzE2NTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9vdVdG7PNMpOt2PxjkQ8z22V1ym7tKCUTb7pZ767aO8)

I have done the needful
