### ISSUE TITLE
[Feature Request]: Add Login/Registration page UI

### ISSUE THREAD

**Issue by DevGajjar28** [Mansi168/EmoWell#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a login/Registration page, so user can login and track the data.

### Use Case

enhance the website, user friendly 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Using Auth0 Oauth isn't there already a sign in and login functionality, I don't see why this is required
