### ISSUE TITLE
[Feature Request]: hey I want to work on your project please assign me

### ISSUE THREAD

**Issue by PAPIYA-DUTTA** [Mansi168/EmoWell#201]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

I want to justify the chat bot chat now section
![imwh](https://github.com/Mansi168/EmoWell/assets/118613949/d5ef63e3-a934-4ef3-8fa2-a236cbc3f488)

### Use Case

I want to change the chat box 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by PAPIYA-DUTTA** [comment]
please assign me

**Comment by PAPIYA-DUTTA** [comment]
please assign mee

**Comment by everly-gif** [comment]
Hi, there's already a PR that addresses this. Please browse our other open issues
