### ISSUE TITLE
[Feature Request]: Add type of feedback section

### ISSUE THREAD

**Issue by AkhilaSunesh** [Mansi168/EmoWell#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/Mansi168/EmoWell/assets/140897461/00d827b1-55a1-423f-800c-c2b6a4d62c4c)

### Use Case

Easy to segregate the feedback forms

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, we don't have a feedback section in the first place but a review form. In the existing review form we have ratings which can communicate a user's satisfaction and  is  also a pretty common ui design. I dont think we need to add a this to the form
