### ISSUE TITLE
[Feature Request]: Improve UI for privacy policy

### ISSUE THREAD

**Issue by AkhilaSunesh** [Mansi168/EmoWell#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Privacy policy is usually not read by the users due to their inadequate UI components.
Adding a hover card will resolve the issue.
It will be arranged in a neat manner. 

### Use Case

Users will read the privacy policy and pay heed to it. They will spend time reading it.

### Benefits

We can add it to the sign up form as a mandatory requirement to read it.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, thanks for the suggestion but the privacy and policy page doesn't require hover cards in my opinion. Keeping in straight to the point like how it currently is better. In case im misunderstanding this, do re open a issue with sample website links or demo screenshots that will help me better understand. Thank you :)
