### ISSUE TITLE
[Feature Request]: contact us should present on home page only 

### ISSUE THREAD

**Issue by siddhant-2002** [Mansi168/EmoWell#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

contact us page is on seprate page it should present on home page only 

### Use Case

so i want to add it on home page 

### Benefits

![image](https://github.com/Mansi168/EmoWell/assets/112260375/bd1cf4cf-e997-4c81-b7a0-5ec6ba33bee5)

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Well, it's okay that it's in a separate page, I don't see why it should be in the homepage. Having a separate contact page in websites is pretty common. Thanks for your suggestion!
