### ISSUE TITLE
[Feature Request]: regester page

### ISSUE THREAD

**Issue by siddhant-2002** [Mansi168/EmoWell#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

register page is not in website so I want to create it in your website 

whenever I clicked on register below page has opened 

### Use Case

![image](https://github.com/Mansi168/EmoWell/assets/112260375/28ee86b2-8dab-4590-8cc7-958e9cfcf500)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, we do have one ! This is issue from configuration in Auth0 which only the admin can fix. You can set up this project locally and see the working login/register page. Thanks.
