### ISSUE TITLE
[Feature Request]:  Improve overall UI of navbar

### ISSUE THREAD

**Issue by Tanishka023** [Mansi168/EmoWell#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar does not look appealing at all, want to make it similar to -
![image](https://github.com/Mansi168/EmoWell/assets/120386924/dd1d9641-164c-4299-9b1c-e7fad5df6d4e)
 

### Benefits

Improve the overall appeal of the site

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, this UI might not suit our website, especially in the navbar. This is more of a footer design. Thanks!
