### ISSUE TITLE
Bug 🐞 Pages Routing Error "404 Page Not Found" After Refreshing.

### ISSUE THREAD

**Issue by MastanSayyad** [Mansi168/EmoWell#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Mansi168 and @everly-gif 

I was just checking the website, and I found that the navigation to the pages only works for a short time. Once refresh the page it shows the following error to the pages **Except Home Page/Components**

![image](https://github.com/Mansi168/EmoWell/assets/101971980/de76a28a-2572-4368-9b9f-830e2303098a)

I have checked for the Pages routes such as **Contact, Review, Register, Privacy and Policy.** These URLs/Links only work for a short time, when you refresh the page, **it shows a 404 page.**

### **#Solution 1:**

- First, we will try by minor changing the path/routes for the pages.

### **#Solution 2:**

After deploying the changed path if the error occurs again then based on my knowledge it only happens if you don't configure your `vercel.json` The routes don't get recognized except the "/" Home page routes. we have to:
-  I'll create a `vercel.json` file to the project.
- add rewrite and redirecting routing rules and configurations
- On the vercel deployment dashboard ensure we pick vitejs as a framework 
- Error Solved !!

### Why It is needed to be fix

This issue is needed to fix as the page routes for other pages will not work after refreshing or redirecting **Except Home Page/Components**, if it does not get resolve then in future additional pages will also encounter the same error, leading to bad user experince

### Add ScreenShots

https://github.com/Mansi168/EmoWell/assets/101971980/fe0b4241-550a-4dd2-bc69-a3fc799112e1

Could you please assign this issue to me under GSSOC 24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi @MastanSayyad please go ahead
