### ISSUE TITLE
Add the Hover Effect in the features section 

### ISSUE THREAD

**Issue by CoderGirl2844** [Mansi168/EmoWell#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add hover effect in the features section 

### Use Case

the hover effect would make the website more interactive.
please assign this issue to me

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
@CoderGirl2844 Thank you for your time. This is already done. You can explore more already existing issues and work on them.
