### ISSUE TITLE
Feature🌟: Add "FAQ Section" to EmoWell Website

### ISSUE THREAD

**Issue by aslams2020** [Mansi168/EmoWell#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @Mansi168 ,
here is the feature request  that i want to suggest - 

I Want to **add a Frequently Asked Questions (FAQ) section** to the Emowell website to enhance user experience by providing quick and easy access to common questions and answers. 
This feature will help users navigate the website more efficiently and find the information they need without extra effort.

**Benefits:**
- Improved User Experience
- Increased Engagement

### Use Case

User Accesses the FAQ Section  To find answers to common questions about the website.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by aslams2020** [comment]
@Mansi168

**Comment by aslams2020** [comment]
@Mansi168

**Comment by everly-gif** [comment]
Sound good @aslams2020
