### ISSUE TITLE
[Documentation Update]: Adding a Code of Conduct md file

### ISSUE THREAD

**Issue by nikki-05** [Mansi168/EmoWell#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The repository currently lacks a code of conduct file, and I want everyone to know the importance of having a code of conduct file. This file will provide guidelines for potential contributors on how to engage with the GSSoC'24 effectively and will document the rules and regulations to follow before diving into the project. Having a code of conduct file will create a safer environment and is considered a good practice. A set of guidelines for GSSoC'24 potential contributors on how to engage with the project effectively. This will be useful to document any rules and regulations to follow before diving into the project.
A code of conduct file provides a safer environment and is considered a good practice
Hence I would like to work on this issue.

### Suggested Change

We can opt for the existing template provided by the GSSoC and later we can make some changes as per our requirement.

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, We already have an issue opened on this before itself. Closing this as duplicate
