### ISSUE TITLE
[Feature Request]: contact page needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [Mansi168/EmoWell#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Contact page needs to be responsive 

### Use Case

![Screenshot_20240625_234425](https://github.com/Mansi168/EmoWell/assets/59639410/a4dea046-3d98-48dd-a17b-4adaebda72c8)

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Go ahead assigning you the issue

**Comment by everly-gif** [comment]
Hi ! @kapilG0 any update?

**Comment by kapilG0** [comment]
> Hi ! @kapilG0 any update?

Hello @Mansi168 i raised pr #258 please check
