### ISSUE TITLE
[Bug]: Register page shows 404 error

### ISSUE THREAD

**Issue by beingPro007** [Mansi168/EmoWell#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After registering and went to my user profile there comes 404 NOT_FOUND error i think the error may be on the vercel app itself

### Add ScreenShots

![Screenshot 2024-06-30 153437](https://github.com/Mansi168/EmoWell/assets/120173992/998615da-b331-460e-b425-ca8f1194bb0a)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Hi, that is because there is no profile route and page created at the moment. So this behavior is expected. If you plan to pitch in the idea for that you can create a separate issue as feature request
