### ISSUE TITLE
Buttons misaligned in feature cards

### ISSUE THREAD

**Issue by MahawarHemlata** [Mansi168/EmoWell#23]
1. Alignment Issue: Buttons Not Aligned Horizontally
2. Button Alignment Problem in ‘Our Features’ Section
![Screenshot 2024-05-09 221208](https://github.com/Mansi168/EmoWell/assets/166614794/267967bd-9dee-4328-b7dd-4e1f762d0093)

**Comment by MahawarHemlata** [comment]
i can fix this issue can you please assign this issue to me under GSSOC'24, PLEASE

**Comment by MahawarHemlata** [comment]
thankyou @Mansi168

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Mansi168
