### ISSUE TITLE
[Bug]: Hover effects on cards

### ISSUE THREAD

**Issue by aanchalpahuja18** [Mansi168/EmoWell#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hover effects on cards can be improved 

### Add ScreenShots

![image](https://github.com/Mansi168/EmoWell/assets/136963878/e232baeb-19dd-4d97-8de0-e7e3a266938b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by aanchalpahuja18** [comment]
@Mansi168 Kindly assign this issue to me I want to solve it

**Comment by everly-gif** [comment]
@aanchalpahuja18 pls proceed

**Comment by everly-gif** [comment]
Hi we already have #16 opened, this issue is a duplicate, Sorry for the inconvenience.
