### ISSUE TITLE
[Feature Request]:  Improving navbar button look

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improving button UI/UX

![image](https://github.com/Mansi168/EmoWell/assets/112775332/ce036ab8-7dbc-4c2f-9b41-de2400a5679c)

### Use Case

This would make the website look more professional type . Right now the button have too much border radius and low padding on x-axis.

### Benefits

This will improve the website look and first impression to the website coz first impression is last impression 

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
@Ayush-may Assigned!
