### ISSUE TITLE
[Bug]: setScrollPosition is not a function

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's a error which says that `setScrollPosition` this is not a function .

![image](https://github.com/Mansi168/EmoWell/assets/112775332/0d34899f-1d2e-452e-a60b-0a82c7d2006c)

### How to resolve the issue
There's a small error it can be fix

![image](https://github.com/Mansi168/EmoWell/assets/112775332/f06897be-317a-4d98-ba30-aa40343ee0bd)

assign me this issue under gssoc'24

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Ayush-may** [comment]
kindly assign me this issue

**Comment by everly-gif** [comment]
@Ayush-may pls proceed
