### ISSUE TITLE
[Feature Request]: Adding an AI Chatbot to the Website

### ISSUE THREAD

**Issue by sanskritisahu21** [Mansi168/EmoWell#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrate an AI-powered chatbot into the website to enhance user interaction, provide instant support, and improve overall user experience.

### Use Case

Chatbot Functionality:
Answer common user queries
Provide information about our services/products
Assist users with navigation on the website

### Benefits

Expected Outcomes:
Improved user engagement and satisfaction
Reduced response time for user inquiries
Enhanced ability to gather user data for future improvements

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanskritisahu21** [comment]
@Mansi168 Please assign me this issue under gssoc

**Comment by everly-gif** [comment]
Hi we do have a chatbot in the application

**Comment by everly-gif** [comment]
Please look into this repo : https://github.com/Mansi168/emowellbeing
