### ISSUE TITLE
Misaligned photos on the "Our Team" page:

### ISSUE THREAD

**Issue by MahawarHemlata** [Mansi168/EmoWell#24]
![Screenshot 2024-05-09 221913](https://github.com/Mansi168/EmoWell/assets/166614794/135f53c4-526e-4fff-b05d-555a96154613)

1. Misaligned Team Member Photos on 'Our Team' Page.
2. Photo Alignment Issue: 'Our Team' Page.
3. Inconsistent Photo Placement in Team Profiles.

**Comment by MahawarHemlata** [comment]
can you please assign this issue to me under GSSOC'24

**Comment by piyushvermaa** [comment]
Can you please assign me. I have good grasp over styling

**Comment by DeepanshuYadav-code** [comment]
### Hello PA
### The images of the team members are not aligned correctly. I will align them correctly based on the structure of the element and modify the shape of the images to make the UI look good.

## Please assign this issue to me under GSSOC 2024

**Comment by Mansi168** [comment]
This section will be removed from the website, so improvements are not needed here. Thanks
