### ISSUE TITLE
[Bug]: open box should come with screen width

### ISSUE THREAD

**Issue by kapilG0** [Mansi168/EmoWell#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240710_235945](https://github.com/Mansi168/EmoWell/assets/59639410/d0d44112-6fe1-4e55-92fc-e85a5b91847d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kapilG0** [comment]
Hello @Mansi168 please assign this issue to me under gssoc 24

**Comment by Agarwalvidu** [comment]
@kapilG0 Thank you for taking time and raising this issue, but I it doesn't need this kind of enhancement that's why I am closing your issue. Please look into more open issues if you can work on it.
