### ISSUE TITLE
 Healthy Minds Happy Lives text can be changed, change the style ot it

### ISSUE THREAD

**Issue by sohinirathor2004** [Mansi168/EmoWell#241]
There's no question that a healthy mind leads to a happy life. The Healthy Minds, Happy Lives website has a lot of great information on how to develop and maintain your mental health. I would suggest checking it out.

While I was browsing the website, I did notice that the font they use for the main text could be better. It's hard to read and not very aesthetically pleasing. I would love to see this website update their font to something more modern and easy on the eyes.

kindly pls look on it !!

**Comment by sohinirathor2004** [comment]
pls look again into it

**Comment by Mansi168** [comment]
hi @sohinirathor2004 i want text of home page with a different style, if you could contribute, pls go ahead.
![image](https://github.com/user-attachments/assets/80844079-30b7-4a2d-89b8-7204bcca01d9)
please experiment on this section, how it can be improved and alligned with rest of the website's design.

**Comment by sohinirathor2004** [comment]
Mobile view 

https://github.com/user-attachments/assets/5337ebb1-666e-4daa-9276-17949c87b749

Tab view

https://github.com/user-attachments/assets/d57e25a3-bfe2-4c93-8e66-ab9606269ddc

Desktop view 

https://github.com/user-attachments/assets/f2847d68-9082-41fa-9260-88b52ca6b6b3
  

Is it  looks nice ?
