### ISSUE TITLE
 Our Team overall div is disturbed and is more aligned towards left

### ISSUE THREAD

**Issue by sohinirathor2004** [Mansi168/EmoWell#244]
I’ve noticed that our Team overall div is disturbed and more aligned towards the left. I’ve tried adjusting it myself but haven’t been able to resolve the issue. Can someone please take a look? It’s been bugging me for a while now.

kindly look on it!!

**Comment by everly-gif** [comment]
Hey, could you clarify? We dont have a our team div? you mean our features?

**Comment by sohinirathor2004** [comment]
yes 

@everly-gif  pls assign me this i will definatly work on this

**Comment by everly-gif** [comment]
It seems pretty center to me :) I cannot assign you this just based on this, if you like to work on alignment and making this section responsive then it would be nice. Do you wanna work on it?

**Comment by sohinirathor2004** [comment]
yes , definately

**Comment by Agarwalvidu** [comment]
@sohinirathor2004 Preparation of Our team section is already mentioned in other issues, so I am closing this issue. Please look into the website and explore more. Thank you!
