### ISSUE TITLE
[Bug]: Nav Links Do Not Scroll to Sections When Accessed from Different Routes

### ISSUE THREAD

**Issue by pani2004** [Mansi168/EmoWell#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When accessing the nav links on the Contact Us page  and clicking on links such as features, about us the page does not scroll to the respective section

### Add ScreenShots

https://github.com/user-attachments/assets/c4c1af00-ac9d-488e-a587-8a3cd2a7a012

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pani2004** [comment]
@Mansi168  @everly-gif Can I work on this?

**Comment by Agarwalvidu** [comment]
@pani2004 Assigned!
