### ISSUE TITLE
[Feature Request]: Addition of Socials for the Team Member

### ISSUE THREAD

**Issue by KomalMaurya** [Mansi168/EmoWell#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I create a section "Our Team" in which team members would be displayed with their social handles.
I will make something like this!!

Name : Komal Maurya
Role : Contributor in GSSoC'24
GitHub Profile link : https://github.com/KomalMaurya
 
Please assign this issue to me!!

![image](https://github.com/user-attachments/assets/7c14ff93-0db9-46f5-a73c-98c8160aa161)

### Use Case

It will make the team come in front to show let users aware of the abilities of Team Members working in the company which would create  a positive impact on the users.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by KomalMaurya** [comment]
@Mansi168 Please assign this issue to me as I've checked your website and I couldn't find The Team Section on it!!

**Comment by Agarwalvidu** [comment]
@KomalMaurya Assigning this issue to you, add the socials of team members
