### ISSUE TITLE
[Feature Request]: Improving Contact form

### ISSUE THREAD

**Issue by MuraliDharan7** [Mansi168/EmoWell#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to improve the contact for as the exists form is looking simple.

![image](https://github.com/user-attachments/assets/73fff236-052f-49ff-9d05-5591925a2303)

### Use Case

Helps the users to understand and give experience at the same time.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
@MuraliDharan7 
Please explain what all changes you want to add.

**Comment by Agarwalvidu** [comment]
I am closing this issue as contact us form is already implemented. Thank you!
