### ISSUE TITLE
[Feature Request]: Alligning all the buttons and images in the same level

### ISSUE THREAD

**Issue by Vedanshimishra** [Mansi168/EmoWell#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to allign all the buttons  and images in the same level and the images width and length should be same.

### Use Case

This would enhance the outlook of the website and make it more appealing.
![Screenshot (254)](https://github.com/user-attachments/assets/3f9b4dd8-dec2-45f7-b704-b596495f42c2)

### Benefits

It would increase the outreach of the website as its outlook would be enhanced and it will be more appealing to the user.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
@Vedanshimishra Assigning this issue to you. Go ahead!

**Comment by sohinirathor2004** [comment]
@Agarwalvidu pls assign me this  is issue i would like to work on this

**Comment by Agarwalvidu** [comment]
Okay @sohinirathor2004 !
Move forward.
