### ISSUE TITLE
[Feature Request]: Add Community Page to Display Project Contributors

### ISSUE THREAD

**Issue by pani2004** [Mansi168/EmoWell#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The community page will display the details of the contributors who have contributed to this project along with repository data using github api.

### Use Case

Since this repo is part of a open source program it would be great to have a community page

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pani2004** [comment]
@Agarwalvidu Can I work on this?

**Comment by everly-gif** [comment]
@pani2004 will this be in Readme.md or in the website ?

**Comment by pani2004** [comment]
@everly-gif It will be in the website

**Comment by everly-gif** [comment]
Alright, the navbar is pretty crowded now so please add the link for this in the footer name it "community" or etc as per your wish. On click it should navigate to new route for this. Add other statistics from the github api as well such as open issues, closed issues and Pull requests counts along with contributors. Give a CTA/button as well which on click will redirect to this repository. Be creative with the UI as this issue is yours. @pani2004 . Let me know if you can handle all of this

**Comment by pani2004** [comment]
@everly-gif These are the data from the api - 
![13 07 2024_20 45 02_REC](https://github.com/user-attachments/assets/b5620d4f-1bdb-4a92-b07a-0b6d0f808e84)
I was thinking to add the avatar of the github profile of the contributor and the no. of contributions made by the contributor and upon clicking the avatar it would redirect to the contributor's github profile. I don't think it is a good idea to add open issues, closed issues and PR as these are a part of the repo not contributor's so I think adding the details of the contributor in the contributor's page would be a good idea. Let me know if this is ok for u or not.

**Comment by everly-gif** [comment]
> @everly-gif These are the data from the api - ![13 07 2024_20 45 02_REC](https://private-user-images.githubusercontent.com/154724111/348480240-b5620d4f-1bdb-4a92-b07a-0b6d0f808e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODU3OTAsIm5iZiI6MTcyMDg4NTQ5MCwicGF0aCI6Ii8xNTQ3MjQxMTEvMzQ4NDgwMjQwLWI1NjIwZDRmLTFiZGItNGE5Mi1iMDdhLTBiNmQwZjgwOGU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxNTQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzIzMjRiOTdiOWM3MWE1MjU2ZjBhNmE5MmI1Zjc0ZDhjYWQ1ZTA4Nzc3NDljYTliY2MzZGFkNGE2MGQzNWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RnQVFqjfnOVziPTGixM49gdir3sacM0G7PJAOTBgdes) I was thinking to add the avatar of the github profile of the contributor and the no. of contributions made by the contributor and upon clicking the avatar it would redirect to the contributor's github profile. I don't think it is a good idea to add open issues, closed issues and PR as these are a part of the repo not contributor's so I think adding the details of the contributor in the contributor's page would be a good idea. Let me know if this is ok for u or not.

I just meant the count of them not the issues themselves ofcourse they belong here, it can make a user interested to contribute as well when they see all this data. Otherwise what's the use of this page on the website when it already exists on Readme.md

**Comment by everly-gif** [comment]
Will get back to you, will get some clarity by visiting websites

**Comment by everly-gif** [comment]
Please view this page : https://appwrite.io/community i meant something like this. Ofcourse this page has lot of features which we don't need to focus. But if u see the top it gives a nice data statistics and below contributors list. Instead of just redirecting to github directly like there you can show the top 50 contributors if possible and then add a view all contributors button.

**Comment by pani2004** [comment]
okk @everly-gif will work on this

**Comment by everly-gif** [comment]
I'm renaming the issue to community page instead of contributors page . Best of luck 😊
