### ISSUE TITLE
Enhancement of UI, maintaining proper color scheme and responsiveness throughout

### ISSUE THREAD

**Issue by Leorasaharia** [Mansi168/EmoWell#26]
1) Revamping the landing page layout to enhance alignment, responsiveness, and color scheme coherence.
2) Improving UI coherence by aligning input and output elements and enhancing overall design aesthetics.
3) Updating the navigation bar with clear, concise, and grammatically correct labels for improved user experience.

**Comment by Leorasaharia** [comment]
@Mansi168 kindly consider my views on this! would be looking forward to contribute and enhance your project!

**Comment by Leorasaharia** [comment]
@Adi-gitX really appreciate you copying the title of my issue and displaying as yours, great job on this achievement, all the best

**Comment by Mansi168** [comment]
hey @Leorasaharia Sure, you can work on it, but please work on the website's pages other than the home page. as other people are working on home page UI enhancement and responsiveness already.

**Comment by Leorasaharia** [comment]
@Mansi168 okay noted, will start working on the ui part for your project asap!!!
