### ISSUE TITLE
Business hours

### ISSUE THREAD

**Issue by SiyaKhetan** [Mansi168/EmoWell#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot (220)](https://github.com/user-attachments/assets/7986154d-05d2-4865-bead-2247a8b7323b)
it seems like the business hours  does not clearly specify what is the proper timings and all .

### Suggested Change

we can properly suggest the timings it is available. It will not look uninformative  as it is at present .This will make the footer more informative and impressive .

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Assigning!
@SiyaKhetan
