### ISSUE TITLE
➕Feature: Implement "Feedback Page" to EmoWell Website 

### ISSUE THREAD

**Issue by aslams2020** [Mansi168/EmoWell#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Mansi168, @everly-gif and @Agarwalvidu 

I want to implement a "Feedback form/page" on the EmoWell website to gather user feedback and improve the Website services. 
The feedback form page **should be accessible from the main navigation** and allow users **to easily provide their thoughts and suggestions.**

### Here's What Will I Do 
- Form Fields **(Name, email, Rating, Feedback)**
- I Will **Add a "Modal" Button** On Clicking which the **Feedback Page will open** (for ex below)
- Additionally, will add a "Tooltip" for the modal feedback button.
- Will Ensure that **email field contains a valid email address.**
- **"Star Rating System" that must be between 1 and 5.**
- **The form will match the current website's design and aesthetics.**
- Provide a **thank you alert upon successful submission.**

**Here's Example of My Previous Work -**

https://github.com/user-attachments/assets/8105c34e-5dd0-4b8e-a2ea-b9d19ce8c66d

### Use Case

Emowell aims to empower individuals in managing their emotional wellbeing effectively through its diverse features. 
**By integrating a feedback form, we can directly capture user insights and preferences.**

Please assign me this issue under GSSoC'24

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
We already have a review form, have you had a look? How will this be different from the review page

**Comment by aslams2020** [comment]
Hey @everly-gif , Thank you for your response!

Yes, I have noticed the existing "review form" earlier. 
My proposal aims to Improve on this by providing a more comprehensive and user-friendly feedback form. 

Also, 
- I Want to make it easily accessible from the main navigation with a **"Modal" button**
- Instead of "Review" Button in Navbar, The "Modal" button  would be better I thought and **an additional "Tooltip".**
- Also, Adding a "Star Rating System" Instead of number system.

Though😅I was going to make a New Feedback Form Earlier, Please share your opinion...

Should I Improve the Existing "Review" Form **with proposed change**s Or Make a New One named "Feedback form"?

**Comment by aslams2020** [comment]
@everly-gif

**Comment by everly-gif** [comment]
Make ur proposed changes to the review form itself. And let if be a route instead of a modal.

**Comment by everly-gif** [comment]
Please confirm you have checked existing issues and this is your own proposal. Will assign this you post that

**Comment by aslams2020** [comment]
@everly-gif , Yes I will make the proposed changes in the Existing Review form!
thankyou

**Comment by aslams2020** [comment]
@Mansi168
