### ISSUE TITLE
[Bug]:  Add the missing "FAQ" link item to the footer

### ISSUE THREAD

**Issue by everly-gif** [Mansi168/EmoWell#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In one of our recent merges, the FAQ link item in the footer was removed by mistake. Although the route already exists. This needs to be added again

### Add ScreenShots

<img width="256" alt="Screenshot 2024-07-14 212813" src="https://github.com/user-attachments/assets/bbe46e5b-f08e-4d92-bebe-914abd248531">

Please add FAQ below Services and it should redirect to **/faq**

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
good first issue open for all! claim it !

**Comment by ramnaresh8** [comment]
I would love to work on it! Could you assign it to me?

**Comment by everly-gif** [comment]
Done ! @ramnaresh8
