### ISSUE TITLE
[Feature Request]: Optimize Accordian

### ISSUE THREAD

**Issue by ramnaresh8** [Mansi168/EmoWell#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

we can make the accordion better by adding + and - icon based on the state. 
For example 
![image](https://github.com/user-attachments/assets/0939f26c-916e-4f1f-ade9-b54fa9f43383)

![image](https://github.com/user-attachments/assets/aa1bd3c3-3af8-4035-aeea-47136ace1785)

### Use Case

It would make the UX better

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Assigning you @ramnaresh8
