### ISSUE TITLE
[Bug]: Improving the Homepage UI improvement

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### issue
The home page isnt looking good , the img is very big and other image is not responsive to the change of screen size 

### what I want to do 
I want to redesign the homepage , everything will be responsive 

### Images 
even this image is not responsive , so i will make this responsive too

![image](https://github.com/user-attachments/assets/7ce01393-5781-427c-ae8e-549c9cac347d)

assign me this issue under gssoc'24

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Ayush-may** [comment]
@Agarwalvidu if u dont mind , can i remove the this image ?

![image](https://github.com/user-attachments/assets/0c668f60-ba9f-447c-ace9-08a82889fdf9)

**Comment by Agarwalvidu** [comment]
Removing the image is not okay, you can come with better ideas for this image

**Comment by Ayush-may** [comment]
> Removing the image is not okay, you can come with better ideas for this image

@Agarwalvidu got it and can u pls add the level to this issue

**Comment by Agarwalvidu** [comment]
I will add the level in your PR.
Happy Coding!

**Comment by Ayush-may** [comment]
@Agarwalvidu 
I thinking to design the navbar like this becoz the previous redesign is taking too much space

![image](https://github.com/user-attachments/assets/0098e599-4649-4169-86d5-3fd9e15f8a67)

this is when im hovering over it 

![image](https://github.com/user-attachments/assets/7627dd3a-f565-4393-9be8-093577288062)
