### ISSUE TITLE
[Feature Request]: Animated 3 circular cursor

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'm thinking to add a animated 3 circular cursor , 
- one will be bigger
- second one will be little smaller
- and third one will be more little smaller than second one 

and all this circle will work smoothly with easy and **follows the cursor direction** 

### preview
right now , this looks little choppy but after some modifications it will look good 

https://github.com/user-attachments/assets/cffb7e1e-29f2-4f19-a203-8cc9c5865c84

### Use Case

This would look cool in the website and gives a better joy experience to its users

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Animated cursor issue is already assigned so closing this issue.
