### ISSUE TITLE
[Feature Request]: Adding a separate page for features

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Since all things have its own page , Im thinking to add a separate page for the features too 

### Use Case

Users can see the features in its own separate page , no confusions there.

### Benefits

Easy to see features and more to know about what is features

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
@Mansi168 Please look into this if you wanted a seperate feature page or not?

**Comment by Agarwalvidu** [comment]
We don't want it. Thank you?
