### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by Bhoovi333** [Mansi168/EmoWell#28]
Hey,
I just saw the emowell app in my phone, though it has creativity and  well designed,

•But I felt it is not responsive in mobile and small screens,if you say I could do that. 
![Screenshot_2024-05-10-13-33-14-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Mansi168/EmoWell/assets/138877556/bb8f90a2-5166-49d4-b704-0f1c17cf6138)

•Also,I think I can made
![Screenshot_2024-05-10-13-33-19-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Mansi168/EmoWell/assets/138877556/55db42d9-b08c-4b71-89f8-d4dd3ae53a65)
 it dynamic,I can add animations to make it more attractive.

**Comment by Raushan0303** [comment]
Can we have a discussion group where we can discuss about the project,?

**Comment by EmazinUs** [comment]
Assign this issue to me i want to work on this under ?GSSOC'24

**Comment by Mansi168** [comment]
hey responsiveness issue is already been taken!
