### ISSUE TITLE
[Bug]: Register is not working 

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Mansi168/EmoWell#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add functional register form

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6d8937aa-b46e-4138-b79a-556b6ab4ba95)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Assigning!
