### ISSUE TITLE
[Bug]: Navbar is hiding on scrolling up

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Mansi168/EmoWell#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar is hiding on scrolling up

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Assigning!
