### ISSUE TITLE
[UI Bug]: Fix Footer Alignment and Enhance Contact Links

### ISSUE THREAD

**Issue by Anni299** [Mansi168/EmoWell#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The 'Our Contacts' heading is not properly aligned.
- Clicking on the phone number and email id should redirect to 'calling' and 'mailto'

### Add ScreenShots

![image](https://github.com/user-attachments/assets/072de878-bc02-47ef-9664-9e7ec7c1b835)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
