### ISSUE TITLE
[Feature Request]: Improve the Ui of searchbar and replace the go button with search icon 

### ISSUE THREAD

**Issue by Riddhi162** [Mansi168/EmoWell#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

GIve the searchbar some color also improve its Ui by giving it rounded borders and hover effect so that it is visible properly with the white background.Kindly assign me under GSSOC'24

### Use Case

The current color of searchbar makes it kind of unnoticeable

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Can you share some ss to validate your issue?

**Comment by Riddhi162** [comment]
![image](https://github.com/user-attachments/assets/b055643d-ca1a-46e1-a0cb-5ea31f264c10)
here its ui is very plain i can make something like this
![image](https://github.com/user-attachments/assets/48b9d496-590a-4e68-b369-b4d2eef3f5b5)
give it some glow or colour related to your website

**Comment by Agarwalvidu** [comment]
Go ahead!
