### ISSUE TITLE
FIX: NAVBAR LINKS

### ISSUE THREAD

**Issue by dinxsh** [Mansi168/EmoWell#29]
all navbar links except home and contact don't work

will add href's for it to direct to right headers respectively

![image](https://github.com/Mansi168/EmoWell/assets/90450035/d41d094e-ed9d-4b5c-bf26-cecdb9a7af96)

**Comment by dinxsh** [comment]
Hi @Mansi168 , could you kindly assign me this issue under gssoc'24

**Comment by Harshitazz** [comment]
i want to work on this

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Mansi168

**Comment by SalehaTabassum** [comment]
Hi @Mansi168 could you please assign this issue to me .i will the nav bar

**Comment by dinxsh** [comment]
kindly review @Mansi168 #51

**Comment by everly-gif** [comment]
Closing issue, as PR has been merged.
