### ISSUE TITLE
[Feature Request]: Correct the text alignment in the games card proper and improve its UI

### ISSUE THREAD

**Issue by Riddhi162** [Mansi168/EmoWell#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The content in the cards of game section is not given margin and padding properly and looks abrupt this can be improved also the cards can be given moving borders to make them look more appealing. Also the blue glow is just not that noticeable.

### Use Case

Since it is a games section it should look sassy 

### Benefits

https://github.com/user-attachments/assets/86a8ea7c-8577-4d9f-9f17-3b414da49395

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
