### ISSUE TITLE
[Bug]: Review Page is not responsive

### ISSUE THREAD

**Issue by Riddhi162** [Mansi168/EmoWell#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The review page is not responsive for the mobile view

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Please add valid ss to your issue

**Comment by Riddhi162** [comment]
Uploading EmoWell - Google Chrome 2024-07-17 22-58-00 (online-video-cutter.com).mp4…

**Comment by Riddhi162** [comment]
https://github.com/user-attachments/assets/1cf369ea-2ac6-4516-ac34-92d76115adc5

**Comment by Agarwalvidu** [comment]
Go ahead!
