### ISSUE TITLE
 🐞[Bug]: Footer Links Do Not Scroll to Top of Page Upon Click

### ISSUE THREAD

**Issue by MastanSayyad** [Mansi168/EmoWell#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @everly-gif @Mansi168 and @Agarwalvidu 

When clicking on the links in the footer, the page does not automatically scroll to the top. Instead, users need to manually scroll up to view the content. This behavior affects user experience and navigation efficiency.

### Add ScreenShots

https://github.com/user-attachments/assets/fd0eea54-86d5-4bed-9ffd-86fdbe5d210d

Upon clicking any link in the footer, the page should smoothly scroll to the top, displaying the relevant section without requiring manual scrolling.

I would like to fix it, coul+d you please assign this issue to me?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
