### ISSUE TITLE
[Feature Request]: About us is not properly responsive

### ISSUE THREAD

**Issue by Priyal208** [Mansi168/EmoWell#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The about us page is not properly centered in mobile view as you can see , if you look very carefully it is more aligned towards right

### Use Case

It look unappealing in mobile view and this is just one use case, it is also dis-aligned in other device sizes alsp

### Benefits

I can fix tht and center it appropriately so that it looks beautiful for all devices
![Screenshot 2024-07-18 132049](https://github.com/user-attachments/assets/99c52c7d-9cb5-4498-963e-fa26f25c275d)
As you can see green div is more towards lefft then it does not look good, I can fix that

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
This issue is already assigned to someone else!
