### ISSUE TITLE
[Feature Request]: Logo doesnt navigate back to home page

### ISSUE THREAD

**Issue by Priyal208** [Mansi168/EmoWell#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It is seen in all websites that logo in navbar when clicked it does redirect to home page but that feature is absent in this website

### Use Case

I can link the logo to the home page so that it is more user friendly and user can directly navigate to home page when he/she wants to

### Benefits

It will enhance user experience 
I mean this logo at navbar as in the image
![Screenshot 2024-07-18 132629](https://github.com/user-attachments/assets/9491025a-874e-43ee-af2b-74295def6f3a)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Gp ahead!
