### ISSUE TITLE
[Feature Request]: Make our features page more attractive

### ISSUE THREAD

**Issue by Priyal208** [Mansi168/EmoWell#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current our features page is very plain and simple and is very common
![Screenshot 2024-07-18 132934](https://github.com/user-attachments/assets/7832204f-3255-4708-b3df-8d148068ff9d)

### Use Case

I can make it more beautiful and attractive which will enhance user experinece

### Benefits

I will add moving gradient border which will amplify look of whole card

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
