### ISSUE TITLE
[Feature Request]: Make buttons more attractive

### ISSUE THREAD

**Issue by Priyal208** [Mansi168/EmoWell#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The button are vrry simple and plain green colored
![Screenshot 2024-07-18 133134](https://github.com/user-attachments/assets/41264878-ed4c-4ae6-ab20-95a4bade9399)

### Use Case

I can make them more eye catchy and attractive and make it look more appealing and beautiful, so that it increases user engagement

### Benefits

I will add more gradient colors and beautiful border and enhance it

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Please add some ss that you want to do!

**Comment by Priyal208** [comment]
something like this glow effect  on hover
![Screenshot 2024-07-18 165832](https://github.com/user-attachments/assets/30035c7d-13b9-4034-9938-f7ecc17dbc7f)
![Screenshot 2024-07-18 170005](https://github.com/user-attachments/assets/62832d07-a30c-4265-9226-63e3376c1c23)

**Comment by Agarwalvidu** [comment]
Okay go ahead! Please keep the colours according to the website!

**Comment by Priyal208** [comment]
sure thanks

**Comment by Priyal208** [comment]
@Agarwalvidu @Mansi168 assign level to this PR, it is not being added to my gssoc points pls look into it
