### ISSUE TITLE
[Bug]: Improving UI of service page

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The service page's box isnt design well 
- There is responsive issue in the card

**Assign me this issue so i can change the followings:**
- change the color of box
- makes little adjustments 
- change button sizes
- any many more according to needs

### issue

![image](https://github.com/user-attachments/assets/00a1a139-6259-4b83-b56f-a389a8ada41d)

![image](https://github.com/user-attachments/assets/1c157069-4325-47bf-a47c-0eee94abd8bc)

![image](https://github.com/user-attachments/assets/93f3ada0-5c2e-4418-8619-26c3d6df013f)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Ayush-may** [comment]
@Agarwalvidu 

![image](https://github.com/user-attachments/assets/69d48583-7ac1-4385-96ba-7cb01b0e4b24)

is this okay if i show the name of service like this ?

**Comment by Ayush-may** [comment]
@Agarwalvidu add level plss

**Comment by Agarwalvidu** [comment]
Done!
