### ISSUE TITLE
[Bug]: Footer little alignment adjustments 

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Theres a little alignments issue in the footer in `our contact` section
- U can see in the image 👇 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bf52e510-b77b-4503-be9b-c6e2d98c53b9)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
This issue is already assigned!
