### ISSUE TITLE
[Feature Request]: Improving the UI of Privacy page

### ISSUE THREAD

**Issue by Ayush-may** [Mansi168/EmoWell#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- Im thinking to add a box in the privacy like **Netflix** , let me show u 
 
![image](https://github.com/user-attachments/assets/3ca77f12-834b-4b5a-b8a6-7bc28014044e)

Users can open and close the box 

![image](https://github.com/user-attachments/assets/e7e6ebf8-0303-4a19-8fb1-a96f95adc280)

### Use Case

It can give more better view for the users 

### Benefits

See the current design isnt looking much good , we can change the way they look and this will give it more better look .

**current design of website** 👇 

![image](https://github.com/user-attachments/assets/e1bc937d-505e-485f-965d-42eb056e348f)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
