### ISSUE TITLE
[Feature Request]: Add Cursor Trail Effect Match to the Website Theme 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Mansi168/EmoWell#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Mansi168 @everly-gif and @Agarwalvidu 

I want to add the cursor trail effect to the website to increase the user experience 

like this

https://github.com/ChromeGaming/Dot-Box/assets/163530398/a163fa6c-0ab6-432d-8afc-6ae26efab341

Could you please assign this issue to me under GSSOC24?

### Use Case

Increases the user experience  and look more engaging  

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
