### ISSUE TITLE
[Feature Request]: Add Scroll Down Progress Bar Matching to Website Design Theme

### ISSUE THREAD

**Issue by MastanSayyad** [Mansi168/EmoWell#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Agarwalvidu, @everly-gif and @man

I would like to suggest adding a scroll down progress bar to the website to enhance user experience. 

like this

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/101971980/1039a5ad-67cf-4dc5-aeb0-8202610c683f)

### Use Case

- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs, docs, and articles.

### Benefits

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction
- Looks more engaging.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
