### ISSUE TITLE
[Feature Request]: Adding hovering and border effects to the features section

### ISSUE THREAD

**Issue by GAVINESHWAR** [Mansi168/EmoWell#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the features section I, there no any effects to the cards of features , So I would like to add the hovering border effects to the section cards.

### Use Case

Making better user interface and user experience to the section.
Making the section more effective.

### Benefits

![image](https://github.com/user-attachments/assets/89ca0c2d-6270-42db-b5f9-794d6b2142f1)]

In this section , i would like to add the effects here.

@Mansi168 , assign me this issue to  make the contribution to the project.

Thank you

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Already done!
