### ISSUE TITLE
Add Privacy Policy page for Information Collection and Use

### ISSUE THREAD

**Issue by kshavp** [Mansi168/EmoWell#32]
A privacy and policy page can be added for Information Collection and Usage and the use of Information.

@Mansi168 assign this issue to me.

**Comment by Mansi168** [comment]
hey, could you please elaborate what are  you thinking of implementing!

**Comment by kshavp** [comment]
Since EmoWell collects user data in the **contact us** and **registration** sections, we can have a privacy policy page that typically informs users about how and where their data is being used just to ease legal transparency.

For Reference : https://www.apple.com/uk/legal/privacy/

**Comment by Mansi168** [comment]
Sure, please go ahead.

**Comment by everly-gif** [comment]
Closing issue, PR has been merged
