### ISSUE TITLE
BUG: The Scroll to Top Button is Only Present in Home Page 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Mansi168/EmoWell#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Mansi168, @everly-gif and @Agarwalvidu 

On this website, the scroll to the top is only present on home page not on other pages.

![image](https://github.com/user-attachments/assets/14698334-88ed-4984-aa00-28914191fab0)

![image](https://github.com/user-attachments/assets/70a73c32-4b9c-485a-9d95-eb8fc822a10e)

Could you please assign this issue to me under GSSOC24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
