### ISSUE TITLE
[Bug]: Fix Navbar Responsiveness

### ISSUE THREAD

**Issue by Kiran-pande-30** [Mansi168/EmoWell#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Navbar is overflowing on the Mobile Screen.

### Add ScreenShots

https://github.com/user-attachments/assets/83569fce-ed2d-4df3-92c4-6237db1f3d23

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Already assigned!
