### ISSUE TITLE
[Bug]: Padding between sections on the HomePage

### ISSUE THREAD

**Issue by Kiran-pande-30** [Mansi168/EmoWell#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is less padding between sections when we navigate to the About Us and Features sections, but the section is not displayed properly.

### Add ScreenShots

https://github.com/user-attachments/assets/ab4bf497-3d8d-4dc1-a852-70328ea26b8e

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
