### ISSUE TITLE
Bug:  Register button disappearing when hovering 

### ISSUE THREAD

**Issue by upsaurav12** [Mansi168/EmoWell#33]
In the navbar of the of home-page the ``register`` button is disappearing when hovering this is the image
![image](https://github.com/Mansi168/EmoWell/assets/116784047/44d7e4c9-13ef-4710-b941-96b6917e2164)

As you can see the Register button's background is disappearing when we hovering mouse in it
So to fix this we can put the border of color ``rgb(48, 175, 91)`` and it will look like this 
![image](https://github.com/Mansi168/EmoWell/assets/116784047/27cd7ba3-1f5c-4930-b756-1a17761f3407)

**Comment by upsaurav12** [comment]
@Mansi168 Pls assign me this issue

**Comment by Mansi168** [comment]
hey sure, please go ahead!

**Comment by upsaurav12** [comment]
Thank you @Mansi168

**Comment by SalehaTabassum** [comment]
Hi @Mansi168 please assign this issue to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Mansi168

**Comment by upsaurav12** [comment]
Hi @Ramu-chiluveru this issue has being assigned to me by the maintainers so you can look on the issues. there are lot of issues out there
thank you

**Comment by Ramu-chiluveru** [comment]
> Hi @Ramu-chiluveru this issue has being assigned to me by the maintainers so you can look on the issues. there are lot of issues out there thank you

Hi @upsaurav12 .yeah okay.

**Comment by Mansi168** [comment]
Hi, @Mansi168 i have solved the issue but it added 2 files, `package.json` and `package-lock.json` so should remove it or commit those changes also ??

Yes, commit it; please make a pull request.

**Comment by Aditya6112** [comment]
Working on this issue @upsaurav12

**Comment by upsaurav12** [comment]
Hey @Aditya6112 you can see that i have already raised a pull request for this issue

**Comment by Aditya6112** [comment]
I have solved the issue #46 .Please review and merge it.

**Comment by upsaurav12** [comment]
Hi pls comment this message in #46 issue page

**Comment by upsaurav12** [comment]
Hi @Mansi168 can you label this issue as level 1 or level 2 for gssoc
