### ISSUE TITLE
[Feature Request]: Implement word limit in Review Page & Contact Form

### ISSUE THREAD

**Issue by Kiran-pande-30** [Mansi168/EmoWell#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to make the following improvements to the review form:

1. Implement a character limit for the name field to ensure it falls within a specified range, preventing submissions with too few or too many characters.
2. Restrict the rating to a value between 1 and 5, ensuring it cannot be negative, and provide appropriate error messages.
3. Set a minimum word limit for the feedback field to prevent submissions with inadequate feedback, such as a single letter.

### Use Case

Word limit will have a neat and clean response form.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Kiran-pande-30** [comment]
@Agarwalvidu please review my PR
