### ISSUE TITLE
Alignment issue in footer

### ISSUE THREAD

**Issue by Anni299** [Mansi168/EmoWell#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The 'Our Contacts' heading is not properly aligned with the rest of the content in the footer. 

### Add ScreenShots

![Screenshot 2024-07-22 003031](https://github.com/user-attachments/assets/2645055a-a8cb-4085-b444-6f30956307e2)
![Screenshot 2024-07-22 003116](https://github.com/user-attachments/assets/8c3ae626-7888-4433-96b2-2052b06946ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
