### ISSUE TITLE
[Bug]: Nav bar menu is not hiding properly on mobile screen

### ISSUE THREAD

**Issue by K-kiran77** [Mansi168/EmoWell#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using the website on mobile screen the nav menu items are not properly hiding the register button is still visible on top even if we close the hamburger menu

### Add ScreenShots

![Screenshot_2024-07-22-06-29-38-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/048a1840-fe04-469f-84a9-62d96805e87d)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
There is already an existing issue #331
