### ISSUE TITLE
[Bug]: Remove trailing cursor in mobile view.

### ISSUE THREAD

**Issue by everly-gif** [Mansi168/EmoWell#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The trailing cursor in mobile view is unresponsive. It's better to address this and remove this as we don't need a cursor in mobile view.

### Add ScreenShots

![Screenshot_20240722_114858_Chrome](https://github.com/user-attachments/assets/717eae08-e45c-4987-984c-6371016c6376)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by MastanSayyad** [comment]
@everly-gif @Agarwalvidu I would like to work on this issue, could you please assign me?

**Comment by everly-gif** [comment]
Sure
