### ISSUE TITLE
Add npm install in readme file

### ISSUE THREAD

**Issue by upsaurav12** [Mansi168/EmoWell#34]
1. When i was trying to setup the codebase i was little bit confused as i have setup properly the codebase form forking the repo to cloning according to the readme file but when i run ``npm run dev`` it was saying ``vite`` was not found so after some research i got to know about npm install so i ran it and then it was fine 
So we can add this also in the repo Readme file so that the ``new-contributor`` can easily setup the codebase in their local system  
2. Also when i was trying to  run ``npm run dev``  it was showing the some error like this
![image](https://github.com/Mansi168/EmoWell/assets/116784047/e4b632bd-b99e-42cf-baf3-5c24ed6c8af2)
 Maybe ``New-contributor`` can also face this issue So to solve this issue we need to run ``npm install @fortawesome/fontawesome-svg-core`` command.We  can also add this

**Comment by upsaurav12** [comment]
Pls assign me this issue

**Comment by Mansi168** [comment]
ok, please npm install just before npm run dev.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Mansi168

**Comment by Mansi168** [comment]
> As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me @Mansi168

It is already assigned!

**Comment by Chaitanya-sesha-govind** [comment]
please check my pull request i have resolved it

**Comment by upsaurav12** [comment]
Hi @Chaitanya-sesha-govind i think you are requesting in wrong place pls request this on your pr and issus page

**Comment by upsaurav12** [comment]
Hi @Mansi168 can you pls label on this issue  as level
