### ISSUE TITLE
[Bug]: contact page css in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [Mansi168/EmoWell#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

contact page is not responsive

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d065cd3b-3c3e-4fc8-8299-649ed4744d37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by prajyot004** [comment]
#339

**Comment by Agarwalvidu** [comment]
Go ahead!
