### ISSUE TITLE
[Bug]: The contact page isn't displaying any data

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Mansi168/EmoWell#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The contact page isn't displaying any data. 

### Add ScreenShots

![Screenshot 2024-07-26 221149](https://github.com/user-attachments/assets/a5cb8fc9-ee6e-4ef8-bd80-9a411ae69a31)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Agarwalvidu** [comment]
Go ahead!
