### ISSUE TITLE
[Bug]: Bug in Mobile View Navbar

### ISSUE THREAD

**Issue by Kiran-pande-30** [Mansi168/EmoWell#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After clicking on sections in the navbar like about and features, navbar is supposed to disappear.

### Add ScreenShots

https://github.com/user-attachments/assets/e721a3e0-da7d-40b5-baf8-a4b1fa5387af

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Kiran-pande-30** [comment]
@Mansi168  @Agarwalvidu Please assign me this issue, I will surely complete it before Tuesday.

**Comment by Agarwalvidu** [comment]
Go ahead!
