### ISSUE TITLE
[Feature Request]:  Css of mental health page i mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [Mansi168/EmoWell#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

page images are not properly aligned 

### Use Case

making responsive
![image](https://github.com/user-attachments/assets/31b1df7b-2f19-4bc7-a0b1-455d771f2df8)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
Please go ahead
