### ISSUE TITLE
Misalignment of Email Field and Lack of Form Validation in Contact Section

### ISSUE THREAD

**Issue by AnantPatel1** [Mansi168/EmoWell#37]
Description:

Issue 1: Misalignment of Email Field:
In the contact section of the Contact, the email field is misaligned, causing a visual inconsistency with the rest of the form elements.

Issue 2: Lack of Form Validation:
Additionally, the contact form lacks proper form validation. Users can submit the form without providing valid credentials, and there is no response or feedback for incorrect or invalid entries.

![Screenshot (27)](https://github.com/Mansi168/EmoWell/assets/106820511/d134deea-0453-46d7-b5ec-30f06dc2bce1)

Note:
Addressing these issues will improve the usability and functionality of the contact section, ensuring a smoother experience for users interacting with the form.

I am interested in working on this issue as part of the GSSOC'24 program

**Comment by AnantPatel1** [comment]
@Mansi168 please assign me this task under GSSOC'24

**Comment by Mansi168** [comment]
Sure, you may start working on it.
