### ISSUE TITLE
BUG🐞: Multiple Scroll Progress Bars Appearing on Scroll

### ISSUE THREAD

**Issue by aslams2020** [Mansi168/EmoWell#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Mansi168 , @everly-gif and @Agarwalvidu ,

I have **encountered a Bug** where **multiple scroll progress bars appear at the top of the page upon scrolling.** 

This results **in three progress bars covering the navbar,** which **negatively impacts the user experience** and visual aesthetics. **There should be only one scroll progress bar at the top of the navbar.**

ISSUE : 

https://github.com/user-attachments/assets/bd4712a0-c408-400c-9de0-b4601b0598f8

### **Here are the details:**
**Expected Behavior:** Only one scroll progress bar should be visible at the top of the navbar
**Actual Behavior:** Three progress bars appear, overlapping and covering the navbar

Please look into this issue and please assign me.
Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by aslams2020** [comment]
@everly-gif @Agarwalvidu I Want to work on this,
Please assign me.

**Comment by everly-gif** [comment]
Please fix the navbar positioning along with it if you can. Thanks and assigned

**Comment by aslams2020** [comment]
> Please fix the navbar positioning along with it if you can. Thanks and assigned
@everly-gif Done Please Check

**Comment by aslams2020** [comment]
@Agarwalvidu @everly-gif @Mansi168 It is Done..please take a look

**Comment by aslams2020** [comment]
@Agarwalvidu @everly-gif @Mansi168 please take a look
