### ISSUE TITLE
bug: About us  page not appearing 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [Mansi168/EmoWell#38]
@Mansi168 There is no About us page linking in Website and on clicking About there is no change happening in the site.

![image](https://github.com/Mansi168/EmoWell/assets/122930278/d7e8d2b7-82a8-41fd-ac01-0fd7a322aa77)

**Comment by ujjwalagrawal-1** [comment]
@Mansi168  Can you **please**  assign this issue to me so that  I can Create About page. under GSSOC'24

**Comment by Mansi168** [comment]
Issue concerning links is already being assigned! Thanks!
