### ISSUE TITLE
Eliminate the duplication of phone no. and email.

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Mansi168/EmoWell#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Eliminate the duplication of phone no. and email.

### Use Case

![image](https://github.com/user-attachments/assets/fd953f39-56be-42c0-8ede-aa0b82af92f6)

### Benefits

Removing duplication of phone and email can improve clarity and organization, reduce errors, and streamline communication processes.

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by everly-gif** [comment]
@Khushi-Pushkar assigned to you
