### ISSUE TITLE
UI improvement Adding Missing pages and Adding Register button App crash BUG

### ISSUE THREAD

**Issue by Venkatknight2295** [Mansi168/EmoWell#42]
![image](https://github.com/Mansi168/EmoWell/assets/118790430/7800fcee-5cbb-412b-8b14-0d07a3f650a5)
This photo is not aligned properly
![image](https://github.com/Mansi168/EmoWell/assets/118790430/bde8dad7-ead3-4ef4-8850-f9833ca0725f)
these are not in uniform shape

Missing About page and when clicked on register app is crashing i will resolve these problems assign me this issue @i-am-SnehaChauhan @Mansi168 @MonalikaPatnaik @anayagithub

**Comment by everly-gif** [comment]
The register button crash can only be fixed by the person who has access to the auth0 dashboard aka the admin. So, I'm closing this issue. Please do browse our other open issues to find one or create your own issues.
