### ISSUE TITLE
Service Page

### ISSUE THREAD

**Issue by sayalisachin** [Mansi168/EmoWell#49]
I think we could have a service page where this website could offer different types of services such as: Indivivual Therapy, Group Support,
Counselling, 24/7 Customer Care. This Page ought to be seperate so as to add to the functionality and moto of the page.  

We can have various features like contact on whatsappp, chatbot, through email, seek support groups and much more!

Can you please Assign me this Issue.
GSSoC Contributor

**Comment by sayalisachin** [comment]
Can you please Assign me this Issue.
GSSoC Contributor

**Comment by Mansi168** [comment]
hey, it seems a good idea.
Please start working on it.
Thanks!

**Comment by sayalisachin** [comment]
Thank you! will do soon!

**Comment by everly-gif** [comment]
Hi @sayalisachin, we haven't heard from you on the progress of the issue. Reassigning to the next interested contributor.

**Comment by everly-gif** [comment]
Hi @Satuti99 , issue is yours

**Comment by Satuti99** [comment]
@everly-gif  Thank you so much  ma'am for assigning me the issue
