### ISSUE TITLE
 [FEAT] Search Bar UI Improvement & Functionality 

### ISSUE THREAD

**Issue by Madhu-mac** [Mansi168/EmoWell#52]
The Search Bar in the reading blog page is not working it is not filtering and the UI is not looking good so we can improve it.

![image](https://github.com/Mansi168/EmoWell/assets/88281761/36530b52-a955-4c31-b5dc-03526e6322c3)

https://github.com/Mansi168/EmoWell/assets/88281761/3e96ef61-b599-4db8-bca2-3859a70fd24e

**Comment by Madhu-mac** [comment]
@Mansi168 Assign me this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by everly-gif** [comment]
Hi, we already seem to have a PR on this. Thank you for raising this issue. Browse are other open issues.
