### ISSUE TITLE
[Bug] Bottom of the Blog Cards have no margin

### ISSUE THREAD

**Issue by Madhu-mac** [Mansi168/EmoWell#53]
Issue: There is no bottom padding/margin in the Reading Area page under the Blog Cards
![image](https://github.com/Mansi168/EmoWell/assets/88281761/467c1493-3663-41ab-a07b-fce5737f3583)

How to produce this issue:

https://github.com/Mansi168/EmoWell/assets/88281761/aa44e3dd-e012-4e04-90c1-ab984ba85248

**Comment by Madhu-mac** [comment]
@Mansi168 Assign me this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by aditya7483thakur** [comment]
Hello Mam ! Please assign me this issue under GSSOC 24

**Comment by everly-gif** [comment]
Hi, there's a PR already that will address it, please browse other open issues
