### ISSUE TITLE
Card issue

### ISSUE THREAD

**Issue by pankaj-bind** [Mansi168/EmoWell#57]
Community Forum card in not properly designed.

![image](https://github.com/Mansi168/EmoWell/assets/73558583/d2120078-0d00-4024-8c72-ca20efa5c5f0)

assign me this work under GSSoC'24, I will correct it.

**Comment by K123Ritesh** [comment]
@pankaj-bind assigned this to you .

**Comment by Mansi168** [comment]
Hey, this issue is alreday being addressed and assinged.
thanks!
