### ISSUE TITLE
Uneven button position

### ISSUE THREAD

**Issue by pankaj-bind** [Mansi168/EmoWell#58]
Buttons in card have uneven position
![gnfgn](https://github.com/Mansi168/EmoWell/assets/73558583/766235e5-2969-4e78-8ee8-5d164e780dfe)

assign me this work under GSSoC'24, I will fix this bug

**Comment by K123Ritesh** [comment]
@pankaj-bind  assigning this issue to you resolve it asap or if any help needed you can reach out to me.

**Comment by K123Ritesh** [comment]
Also @pankaj-bind reaolve this in such a way so that don't get distorted in different screen sizes..hope you got it..

**Comment by pankaj-bind** [comment]
Don't worry, I'll take care of that.

**Comment by Mansi168** [comment]
hey sorry for the misunderstanding, but this issue has already been resolved!
thanks!

**Comment by pankaj-bind** [comment]
No worry. Would you please look for issue #59 and #60.
