### ISSUE TITLE
Footer dialer feature 

### ISSUE THREAD

**Issue by pankaj-bind** [Mansi168/EmoWell#59]
I can implement a feature so that if user click on this it will redirect him to their phone's dialer pad with this phone number.
![image](https://github.com/Mansi168/EmoWell/assets/73558583/60272f9e-6c7b-45b3-b806-a8e6a6cf1ebe)

assign me this work under GSSoC'24, I will implement it.

**Comment by everly-gif** [comment]
Please go ahead
