### ISSUE TITLE
Bug: Responsiveness in Mobile

### ISSUE THREAD

**Issue by mukulpythondev** [Mansi168/EmoWell#61]
Emowell is not responsive in mobile. 
## Page 1
![Section 1](https://github.com/Mansi168/EmoWell/assets/134795697/04daa2fa-3322-441a-9f35-20ab17beb6eb)
![Section 2](https://github.com/Mansi168/EmoWell/assets/134795697/08de9de1-44b5-4ec0-b1da-6ef5f0e58f41)
![Section 3](https://github.com/Mansi168/EmoWell/assets/134795697/f2e30205-f936-4a98-b727-e8b33bd075dd)

**Comment by mukulpythondev** [comment]
I happy to work on this project. please assign to me.

**Comment by K123Ritesh** [comment]
@mukulpythondev i am assigning this issue to you solve it and if need help or guide then you can reach out to me..

**Comment by Mansi168** [comment]
This issue is alreday been assigned.
Thanks!
