### ISSUE TITLE
Button Placement in the cards of  'Our Features' section

### ISSUE THREAD

**Issue by BagchiShreya** [Mansi168/EmoWell#63]
The buttons in 'Our Features' section are placed at different heights. By making sure that all the buttons are on the same level, the visual appeal of this website would increase.
![image](https://github.com/Mansi168/EmoWell/assets/106909868/be3fee2d-fa40-4b96-b39a-e935b73a977c)

**Comment by BagchiShreya** [comment]
Hello @Mansi168 
I would like to work on this issue and resolve it to make the website even more visually appealing. As I have worked on similar issues and also raised a number of PRs, I think I would be able to work on this issue. It would be great if you assign this issue to me.
This would be a GSSoC'24 contribution.

**Comment by CODER-Rxj11** [comment]
Greeting **_@Mansi168_** 

I would like to work on refinement in the alignment of buttons within the cards of the 'Our Features' section. 
Ensuring uniformity in button placement across all cards will significantly enhance the visual coherence of the website design. 

As someone who has done this before, I can also promise that it will look better in a couple of times.
Thanks!!

**Comment by everly-gif** [comment]
Hi, we already have a PR for this issue. Please browse our other open issues.
