### ISSUE TITLE
Changing the background colour of the website.

### ISSUE THREAD

**Issue by BagchiShreya** [Mansi168/EmoWell#65]
The white background colour makes the text on the landing page a bit difficult to read. Changing it to a different colour similar to white would resolve the issue.
![image](https://github.com/Mansi168/EmoWell/assets/106909868/e8fbcf09-f4a2-44a3-aa17-5ff98c371441)

**Comment by BagchiShreya** [comment]
Hello @Mansi168 
I would like to work on this issue and resolve it to make the website even more visually appealing. As I have worked on similar issues and also raised a number of PRs, I think I would be able to work on this issue. It would be great if you assign this issue to me.
This would be a GSSoC'24 contribution.

**Comment by Aditya6112** [comment]
Hey! @Mansi168 I want to work on this issue Please assign this to me.

**Comment by ashish027120** [comment]
@Mansi168 Can You Please Assign This Task To Me , I Want To Work In This Issue .

**Comment by Mansi168** [comment]
UI improvement issues are already assigned.
Thanks!

**Comment by ashish027120** [comment]
> UI improvement issues are already assigned. Thanks!

Ok
