### ISSUE TITLE
Feature section and footer UI Improvement

### ISSUE THREAD

**Issue by VishalGaurav01** [Mansi168/EmoWell#66]
Create a responsive footer and enhance the user experience of the website
![Screenshot 2024-05-12 132236](https://github.com/Mansi168/EmoWell/assets/97465452/9e9dfbe3-67ab-4847-b384-bf064254a894)
Assignee: I have successfully contributed to previous tasks under GSOOC'24 and looking to make an impactful contribution to this website....please assign this issue to me.

**Comment by Mansi168** [comment]
This issue is already assigned! 
Thanks!
