### ISSUE TITLE
The page is not responsive along width taking extra width

### ISSUE THREAD

**Issue by upsaurav12** [Mansi168/EmoWell#69]
In the ``main-page`` when we set the page we can see the unresponsiveness of the page along width.
We can fix this by setting the width to 100 vw or else we can consider other methods

[cinnamon-2024-05-12T192702+0530.webm](https://github.com/Mansi168/EmoWell/assets/116784047/712d36c7-6120-44f1-80a4-730a950836f1)

You can see the issue by clicking the video

**Comment by upsaurav12** [comment]
Pls assign me this issue 
thank you

**Comment by Mansi168** [comment]
Ok, but please work on this width issue only.

**Comment by NitinChakrawarti** [comment]
he'll @Mansi168  i want to contribute  in this issue under GSSoC'24,

I am experienced in media queries and making website responsive and adaptive.

**Comment by sahithinandikula** [comment]
@Mansi168  I am interested in working on the issue. consider my request and assign it

**Comment by Agarwalvidu** [comment]
This issue has been resolved. Thank you for contributing. Looking for more issues from your side.
