### ISSUE TITLE
Regrading website animations

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Mansi168/EmoWell#70]
Hi i am Ram from
#gssoc2024
i want to add some cool animations in your website which looks good and interactive improved UI
tech stack to be used
-AOS.js for (scrolling animations)
-ityped.js
-tilt.js

**Comment by RamakrushnaBiswal** [comment]
@Mansi168 please assign it to me

**Comment by Mansi168** [comment]
Hey, issues are assigned for ui improvements of the websites. So please make sure your work doesnt conflict with others.
I would suggest first wait for the ui improvement and then you can add your work.

**Comment by RamakrushnaBiswal** [comment]
hi @everly-gif review the PR

**Comment by Agarwalvidu** [comment]
@RamakrushnaBiswal Please review you PR it has conglicts.

**Comment by RamakrushnaBiswal** [comment]
@Agarwalvidu i will create a new PR this PR has too mush conflicts ig

**Comment by Agarwalvidu** [comment]
@RamakrushnaBiswal okay then I am closing this PR. Make sure to sync the repo before creating the new PR. Thank you.

**Comment by RamakrushnaBiswal** [comment]
@Agarwalvidu done mam
