### ISSUE TITLE
Adding login and signup page.

### ISSUE THREAD

**Issue by Omi006** [Mansi168/EmoWell#74]
**Described feature**
Hey, their I want to add login and signup page to your website. 

**Output Screenshot**
This will be the login page
![Screenshot 2024-05-13 113802](https://github.com/Mansi168/EmoWell/assets/113918394/968dd7ef-9096-4f41-8e4d-dc39e92d22cc)

This will be the Sign-in Form
![Screenshot 2024-05-13 113822](https://github.com/Mansi168/EmoWell/assets/113918394/12cd245c-2dc0-44e9-8e56-932f981e38a4)

I will make it suitable infought, that it will look good with other website UI also.
Requesting you to assign me this issue under Gssoc'24.

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by Riyasharma1311** [comment]
please assign me this

**Comment by Anuhk** [comment]
I would like the opportunity to work on it , please label this issue and assign

**Comment by everly-gif** [comment]
Hi, this functionality is there. The project uses Auth0 OAuth to handle authentication
