### ISSUE TITLE
Feature:Add a mental assessment tests links in features

### ISSUE THREAD

**Issue by Hrishita-Paul** [Mansi168/EmoWell#76]
Add an option in feature redirecting to links of popular mental health assessment, their meaning, it will enhance the help provided by this site in promoting mental heath awareness.

**Comment by Hrishita-Paul** [comment]
@i-am-SnehaChauhan , please assign this issue to me under GSSoC .I am a Frontend Web Developer, core member of GDSC,NIT Silchar and I am quite aware about such tests and their helpfulness in promoting the essence of EmoWell.

**Comment by SwastiShankhdhar** [comment]
> Add an option in feature redirecting to links of popular mental health assessment, their meaning, it will enhance the help provided by this site in promoting mental heath awareness.

I WANT TO DO THISISSUE , PLEASE ASSIGN IT TO ME

**Comment by Mansi168** [comment]
@Hrishita-Paul Hey, please go ahead!
