### ISSUE TITLE
Contact form layout and alignment

### ISSUE THREAD

**Issue by lazybug19** [Mansi168/EmoWell#78]
![image](https://github.com/Mansi168/EmoWell/assets/105040967/8c27ce2e-9168-49fa-8712-ce8b2dc53a28)

@Mansi168  As it can be seen in the image, the contact form doesn't fit within the screen size ratio and layout seems off. I would like to work on improving this under GSSoC'24.

**Comment by Mansi168** [comment]
Hey, this issue is already assigned!
