### ISSUE TITLE
[Bug] : Navigation bar moving 

### ISSUE THREAD

**Issue by sivaprasath2004** [Mansi168/EmoWell#79]
- The `Resigter` button we will hover the hole navigation content can be moving `left` side 0.5rem.
- In this bug doen't accessable in the navigation bar.

### Bug 
[Screencast from 2024-05-13 17-43-17.webm](https://github.com/Mansi168/EmoWell/assets/121082414/23b301c8-e7dd-4d06-92cc-45d0d9214440)

**Comment by Mansi168** [comment]
Hey, thanks for reporting; you may work on it.

**Comment by everly-gif** [comment]
Closing issue, PR merged
