### ISSUE TITLE
hover effect missing and no responsiveness 

### ISSUE THREAD

**Issue by sahithinandikula** [Mansi168/EmoWell#80]
issues exist on the web page : 
adding hover effect 
 
![Screenshot 2024-05-13 175629](https://github.com/Mansi168/EmoWell/assets/138794574/ca0ea8db-a0c9-4025-9b18-2f116d1263f3)
also the responsiveness is missing here
 
 
![Screenshot 2024-05-13 175042](https://github.com/Mansi168/EmoWell/assets/138794574/a4a9d152-f45b-4b02-97ce-a2a1ed6062a5)

the issue can be solved  by adding the hover effect and making the website more responsive to  enhance the UI

**Comment by Mansi168** [comment]
These issues are already assigned! Thanks!
