### ISSUE TITLE
[ Minor Fix ] : "About" link in the footer 

### ISSUE THREAD

**Issue by kshavp** [Mansi168/EmoWell#90]
## Description
The about link in the footer section needs to navigate to the about section as it works in the navbar.

## Expected Behaviour
On clicking the about link in the footer refreshes the site instead of navigating to the about section.

@Mansi168 I would give it a quick fix, if seems relevant you may assign it to me. Thank you.

https://github.com/Mansi168/EmoWell/assets/95236968/52f4f2cd-4398-4002-a341-d15310625af7

**Comment by Mansi168** [comment]
The issue concerning footer is already assigned.
Thanks!
