### ISSUE TITLE
UI Improvement of Contact page

### ISSUE THREAD

**Issue by sahithinandikula** [Mansi168/EmoWell#91]
The contact page is not visually appealing .
![image](https://github.com/Mansi168/EmoWell/assets/138794574/bad7bb14-6767-4d9e-a9bc-d11f55c40eb0)
the color, font and responsiveness can be enhanced

**Comment by sahithinandikula** [comment]
@Mansi168 Kindly assign this issue and label it to start my contribution

**Comment by Mansi168** [comment]
it is already assigned.
