### ISSUE TITLE
Adding social media icons

### ISSUE THREAD

**Issue by Syed0206** [Mansi168/EmoWell#95]
I would like to add social media icons like Github,Facebook icons to the website  @Mansi168 can you please assign me this issue under GSSOC'24.

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by GnanariddhikaRavikumar** [comment]
I can add more visible and good looking icons using toastify.Could you assign me this issue under GSSOC'24
