### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by Nikhilesh002** [Mansi168/EmoWell#96]
Route not found error page is not present.

![image](https://github.com/Mansi168/EmoWell/assets/134734453/e8a33fdb-71ef-4768-b8bb-e35ee597706e)

I will create a new error route for all undefined routes. Please assign me this task with required labels for gssoc24.

**Comment by Mansi168** [comment]
sure, please work on it!

**Comment by Nikhilesh002** [comment]
Thanks for assigning. Started working on it.

**Comment by Nikhilesh002** [comment]
Please explain me details how you want the page to look like

**Comment by sristy17** [comment]
@Mansi168 I know the Solution for this, if possible please assign me.

**Comment by Nikhilesh002** [comment]
I am doing this

**Comment by lassmara** [comment]
Please assign me this issue

**Comment by everly-gif** [comment]
@Nikhilesh002, there has been no update on the issue for 3 weeks. Unfortunately will have to assign this to next interested contributor

**Comment by sristy17** [comment]
> @Nikhilesh002, there has been no update on the issue for 3 weeks. Unfortunately will have to assign this to next interested contributor

I would like to work on this issue!

**Comment by sristy17** [comment]
> @Nikhilesh002, there has been no update on the issue for 3 weeks. Unfortunately will have to assign this to next interested contributor

I would like to work on this issue!

**Comment by everly-gif** [comment]
@sristy17 the issue is yours.

**Comment by sristy17** [comment]
> @sristy17 the issue is yours.

Thanks by tomorrow I will be creating a pr!

**Comment by Nikhilesh002** [comment]
> @Nikhilesh002, there has been no update on the issue for 3 weeks. Unfortunately will have to assign this to next interested contributor

Hey @everly-gif , I have raised pr long ago. Please look prs

**Comment by everly-gif** [comment]
I see. That PR had no issue linked before, hence why the previous comment. Please link it with issue #96 in the description so that we know which issue the PR solves and mix-ups like this can be avoided in the future. @sristy17 please hold off, as per practice @Nikhilesh002 takes precedence and has already worked on it. Sorry for the mixup :)

**Comment by sristy17** [comment]
> I see. That PR had no issue linked before, hence why the previous comment. Please link it with issue #96 in the description so that we know which issue the PR solves and mix-ups like this can be avoided in the future. @sristy17 please hold off, as per practice @Nikhilesh002 takes precedence and has already worked on it. Sorry for the mixup :) 

Actually I was trying to fetch the previous details on routing where he created an error page!

**Comment by Nikhilesh002** [comment]
> I see. That PR had no issue linked before, hence why the previous comment. Please link it with issue #96 in the description so that we know which issue the PR solves and mix-ups like this can be avoided in the future. @sristy17 please hold off, as per practice @Nikhilesh002 takes precedence and has already worked on it. Sorry for the mixup :)


sorry, I put pr no instead of issue no

**Comment by Nikhilesh002** [comment]
@everly-gif  @Mansi168   pls merge

**Comment by everly-gif** [comment]
merged
